# Generated by Django 3.2.23 on 2023-12-04 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0005_auto_20231203_2332'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='eventdate',
            table='event_date',
        ),
    ]
