# Generated by Django 3.2.23 on 2023-12-04 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0006_alter_eventdate_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='eventdate',
            table='eventdate',
        ),
    ]
