# Generated by Django 3.2.23 on 2023-12-04 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0007_alter_eventdate_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='event',
            name='recurring',
        ),
    ]
