# Generated by Django 3.2.23 on 2023-12-04 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0008_auto_20231204_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='owner',
        ),
    ]
